(ns ^:no-doc co.multiply.quiescent.type.call
  "Platform-unifying call shims for the task interfaces.

   On the JVM the task types implement hand-written Java interfaces
   (`co.multiply.quiescent.impl.ITask` & co) so calls compile to direct,
   reflection-free `invokeinterface` with primitive signatures. On CLJS the
   same names are declared as protocols in `co.multiply.quiescent.type`.

   Each shim here is a macro that expands to a qualified interface call on
   CLJ and a protocol call on CLJS, so call sites are identical `.cljc`.
   The shims are generated by `defshim`; only `doApply` (which has real
   logic) is hand-written.

   Everything is inside a `#?(:clj ...)` branch: macros only exist on the
   CLJ side of a `.cljc`, and letting the CLJS pass see the `defshim` calls
   would compile them as calls to an undefined runtime function."
  #?(:cljs (:require-macros co.multiply.quiescent.type.call))
  (:require
    [co.multiply.quiescent.util :refer [if-cljs]]
    [co.multiply.quiescent.type :as type])
  #?(:clj (:import [co.multiply.quiescent.impl TaskState])))


#?(:clj
   (do

     (defmacro ^:private defshim
       "Define a call shim for a method of `iface`.

        Each arity is either a plain arglist — arguments are passed through
        as-is — or an `(arglist call-args)` pair, where `call-args` are the
        forms passed to the underlying method, letting shorter arities fill
        in defaults."
       [iface method & arities]
       (let [proto-sym (symbol "co.multiply.quiescent.type" (name method))
             iface-sym (symbol (str "co.multiply.quiescent.impl." (name iface))
                         (str "." (name method)))
             arity     (fn [spec]
                         (let [[params args] (if (vector? spec) [spec spec] spec)]
                           (list params
                             (list `if-cljs
                               (list* `list (list 'quote proto-sym) args)
                               (list* `list (list 'quote iface-sym) args)))))]
         `(defmacro ~method ~@(map arity arities))))


     ;; ## IStateful
     (defshim IStateful isExceptional [this])
     (defshim IStateful isCancelled [this])
     (defshim IStateful isCompelled [this])
     (defshim IStateful getPhase [this])
     (defshim IStateful getResult [this])
     (defshim IStateful getSubscriptions [this])
     (defshim IStateful getScope [this])
     (defshim IStateful setScope [this new-scope])
     (defshim IStateful atOrPast [this phase])


     ;; ## ICancellable
     (defshim ICancellable doCancel [this msg])
     (defshim ICancellable doCancelCascade [this])
     (defshim ICancellable doCancelDirect [this])


     ;; ## ITask
     ;; Query
     (defshim ITask getNow [this default])
     (defshim ITask newQuiescenceProxy
       ([this] [this true])
       [this default])

     ;; Entry points
     (defshim ITask doRun
       ([this f] [this f nil])
       [this f tf])

     ;; Phases
     (defshim ITask doGround
       ([this f] [this f nil])
       [this f tf])
     (defshim ITask doTransform [this res tf])
     (defshim ITask doWrite [this task-state])
     (defshim ITask doSettle [this])
     (defshim ITask doQuiesce [this])

     ;; Subscription
     (defshim ITask doSubscribe [this sub])
     (defshim ITask doUnsubscribe [this sub])
     (defshim ITask runSubscriptions [this])

     ;; Chain transformations
     (defshim ITask doThen [this executor f])
     (defshim ITask doHandle [this executor f])
     (defshim ITask doCatch [this executor f])
     (defshim ITask doCatchTyped [this executor f])

     ;; Chain side-effects
     (defshim ITask doOk [this executor f])
     (defshim ITask doErr [this executor f])
     (defshim ITask doDone [this executor f])

     ;; Chain teardown/cleanup
     (defshim ITask doFinally [this executor f])


     (defmacro doApply
       ([this v]
        `(co.multiply.quiescent.type.call/doGround ~this ~v))
       ([this v e]
        `(let [e# ~e]
           (if e#
             (co.multiply.quiescent.type.call/doWrite ~this
               (if-cljs
                 (type/TaskState. true false e#)
                 (TaskState. true false e#)))
             (co.multiply.quiescent.type.call/doGround ~this ~v))))
       ([this v e tf]
        `(let [e# ~e]
           (if e#
             (co.multiply.quiescent.type.call/doWrite ~this
               (if-cljs
                 (type/TaskState. true false e#)
                 (TaskState. true false e#)))
             (co.multiply.quiescent.type.call/doGround ~this ~v ~tf)))))))
